"""Generate Cursor rule files from profile data."""

from __future__ import annotations

from pathlib import Path

from nblane.core.paths import REPO_ROOT


def write_nblane_context_rule(profile: str) -> Path:
    """Write ``.cursor/rules/nblane-context.mdc`` with a profile summary."""
    from nblane.mcp_server import build_summary_text

    summary = build_summary_text(profile)
    rules_dir = REPO_ROOT / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    path = rules_dir / "nblane-context.mdc"
    body = (
        "---\n"
        "description: nblane profile summary (nblane sync-cursor)\n"
        "globs:\n"
        "alwaysApply: false\n"
        "---\n\n"
        f"<!-- profile: {profile} — generated by "
        f"`nblane sync-cursor` -->\n\n"
        + summary
        + "\n\n---\n"
        "Prefer live data via MCP resources `profile://summary` and "
        "`profile://context` when the nblane MCP server is enabled.\n"
    )
    path.write_text(body, encoding="utf-8")
    return path
