"""Growth Graph contract shared by docs, read models, and UI payloads."""

from __future__ import annotations

import copy
import re
from pathlib import Path
from typing import Any

import yaml

from nblane.core.paths import REPO_ROOT

CONTRACT_SCHEMA_VERSION = "1.0"
GROWTH_GRAPH_DOC = REPO_ROOT / "docs" / "zh" / "product" / "growth-graph.md"

_CONTRACT_BLOCK_RE = re.compile(
    r"```yaml\s+growth_graph_contract\s*\n(?P<body>.*?)\n```",
    re.DOTALL,
)

_DEFAULT_CONTRACT: dict[str, Any] = {
    "schema_version": CONTRACT_SCHEMA_VERSION,
    "layers": [
        {"id": "direction", "label": "Direction", "label_zh": "方向"},
        {"id": "objective", "label": "Objective", "label_zh": "目标"},
        {"id": "work_context", "label": "Work Context", "label_zh": "工作语境"},
        {"id": "activity", "label": "Activity", "label_zh": "活动"},
        {"id": "source", "label": "Source", "label_zh": "来源"},
        {"id": "evidence", "label": "Evidence", "label_zh": "证据"},
        {"id": "claim", "label": "Claim", "label_zh": "断言"},
        {"id": "capability", "label": "Capability", "label_zh": "能力"},
        {"id": "output", "label": "Output", "label_zh": "输出"},
        {"id": "feedback", "label": "Feedback", "label_zh": "反馈"},
        {"id": "governance", "label": "Governance", "label_zh": "治理"},
    ],
    "node_types": [
        {"id": "north_star", "layer": "direction", "label": "North Star", "label_zh": "长期方向"},
        {"id": "goal", "layer": "objective", "label": "Goal", "label_zh": "阶段目标"},
        {"id": "project_case", "layer": "work_context", "label": "Project Case", "label_zh": "项目案例"},
        {"id": "task", "layer": "activity", "label": "Task", "label_zh": "任务"},
        {"id": "daily_work", "layer": "activity", "label": "Daily Work", "label_zh": "日常工作"},
        {"id": "research", "layer": "activity", "label": "Research", "label_zh": "研究"},
        {"id": "agent_run", "layer": "activity", "label": "Agent Run", "label_zh": "Agent 运行"},
        {"id": "source", "layer": "source", "label": "Source", "label_zh": "来源"},
        {"id": "evidence_candidate", "layer": "evidence", "label": "Evidence Candidate", "label_zh": "证据候选"},
        {"id": "atomic_evidence", "layer": "evidence", "label": "Atomic Evidence", "label_zh": "原子证据"},
        {"id": "composite_evidence", "layer": "evidence", "label": "Composite Evidence", "label_zh": "组合证据"},
        {"id": "claim", "layer": "claim", "label": "Claim", "label_zh": "断言"},
        {"id": "skill", "layer": "capability", "label": "Skill", "label_zh": "技能"},
        {"id": "gap", "layer": "capability", "label": "Gap", "label_zh": "缺口"},
        {"id": "next_action", "layer": "capability", "label": "Next Action", "label_zh": "下一步行动"},
        {"id": "output", "layer": "output", "label": "Output", "label_zh": "输出"},
        {"id": "feedback", "layer": "feedback", "label": "Feedback", "label_zh": "反馈"},
        {"id": "capacity", "layer": "governance", "label": "North Star Capacity", "label_zh": "方向容量"},
        {"id": "health", "layer": "governance", "label": "Health", "label_zh": "健康"},
    ],
    "edge_types": [
        {"id": "alignment", "label": "Alignment", "label_zh": "对齐"},
        {"id": "contains", "label": "Contains", "label_zh": "包含"},
        {"id": "generated_by", "label": "Generated by", "label_zh": "生成自"},
        {"id": "source_to_candidate", "label": "Source to candidate", "label_zh": "来源到候选"},
        {"id": "review", "label": "Review", "label_zh": "审阅"},
        {"id": "derives", "label": "Derives", "label_zh": "派生"},
        {"id": "supports", "label": "Supports", "label_zh": "支撑"},
        {"id": "drives", "label": "Drives", "label_zh": "驱动"},
        {"id": "produces", "label": "Produces", "label_zh": "产出"},
        {"id": "feedback", "label": "Feedback", "label_zh": "反馈"},
        {"id": "watches", "label": "Watches", "label_zh": "监控"},
    ],
}


def _clean_text(value: object) -> str:
    return str(value or "").strip()


def _clean_rows(raw: object, *, require_layer: bool = False) -> list[dict[str, str]]:
    rows = raw if isinstance(raw, list) else []
    out: list[dict[str, str]] = []
    seen: set[str] = set()
    for item in rows:
        if not isinstance(item, dict):
            continue
        row_id = _clean_text(item.get("id"))
        if not row_id or row_id in seen:
            continue
        row = {
            "id": row_id,
            "label": _clean_text(item.get("label")),
            "label_zh": _clean_text(item.get("label_zh")),
        }
        if require_layer:
            row["layer"] = _clean_text(item.get("layer"))
        out.append(row)
        seen.add(row_id)
    return out


def _normalize_contract(raw: dict[str, Any] | None) -> dict[str, Any]:
    source = raw if isinstance(raw, dict) else {}
    contract = copy.deepcopy(_DEFAULT_CONTRACT)
    layers = _clean_rows(source.get("layers"))
    if layers:
        contract["layers"] = layers
    layer_ids = {row["id"] for row in contract["layers"]}

    node_types = [
        row
        for row in _clean_rows(source.get("node_types"), require_layer=True)
        if row.get("layer") in layer_ids
    ]
    if node_types:
        contract["node_types"] = node_types

    edge_types = _clean_rows(source.get("edge_types"))
    if edge_types:
        contract["edge_types"] = edge_types

    contract["schema_version"] = (
        _clean_text(source.get("schema_version")) or CONTRACT_SCHEMA_VERSION
    )
    return contract


def _contract_from_doc(path: Path = GROWTH_GRAPH_DOC) -> dict[str, Any] | None:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    match = _CONTRACT_BLOCK_RE.search(text)
    if match is None:
        return None
    try:
        raw = yaml.safe_load(match.group("body")) or {}
    except yaml.YAMLError:
        return None
    return raw if isinstance(raw, dict) else None


def growth_graph_contract(path: Path = GROWTH_GRAPH_DOC) -> dict[str, Any]:
    """Return the normalized Growth Graph contract.

    The product document is the preferred source. A built-in copy keeps tests
    and old checkouts usable when the machine-readable block is missing.
    """

    return _normalize_contract(_contract_from_doc(path))


def growth_graph_layers(path: Path = GROWTH_GRAPH_DOC) -> tuple[str, ...]:
    """Return stable Growth Graph layer ids."""

    return tuple(row["id"] for row in growth_graph_contract(path)["layers"])


def growth_graph_node_types(path: Path = GROWTH_GRAPH_DOC) -> tuple[str, ...]:
    """Return supported Growth Graph node type ids."""

    return tuple(row["id"] for row in growth_graph_contract(path)["node_types"])


def growth_graph_edge_types(path: Path = GROWTH_GRAPH_DOC) -> tuple[str, ...]:
    """Return supported Growth Graph edge type ids."""

    return tuple(row["id"] for row in growth_graph_contract(path)["edge_types"])


def growth_graph_node_type_layers(path: Path = GROWTH_GRAPH_DOC) -> dict[str, str]:
    """Return node type -> layer mapping."""

    return {
        row["id"]: row["layer"]
        for row in growth_graph_contract(path)["node_types"]
        if row.get("layer")
    }


def growth_graph_payload(path: Path = GROWTH_GRAPH_DOC) -> dict[str, Any]:
    """Return a JSON-safe contract payload for clients."""

    return copy.deepcopy(growth_graph_contract(path))


__all__ = [
    "CONTRACT_SCHEMA_VERSION",
    "GROWTH_GRAPH_DOC",
    "growth_graph_contract",
    "growth_graph_edge_types",
    "growth_graph_layers",
    "growth_graph_node_type_layers",
    "growth_graph_node_types",
    "growth_graph_payload",
]
