"""Configurable visual generation helpers for public blog assets."""

from __future__ import annotations

import base64
import hashlib
import json
import mimetypes
import os
import re
import shutil
import subprocess
import time
import uuid
from dataclasses import dataclass, field
from email.utils import formatdate
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, unquote, urlparse
from urllib.request import Request, urlopen

from nblane.core import llm
from nblane.core.ai_blog_prompts import get_prompt

DEFAULT_PROVIDER = "dashscope_wan"
DEFAULT_IMAGE_MODEL = "wan2.7-image-pro"
DEFAULT_IMAGE_FAST_MODEL = "wan2.7-image"
DEFAULT_IMAGE_LEGACY_MODEL = "wan2.1-t2i-turbo"
DEFAULT_VIDEO_MODEL = "wan2.7-videoedit"
DEFAULT_COVER_SIZE = "1536*864"
DEFAULT_DIAGRAM_SIZE = "1440*1440"
DEFAULT_EXAMPLE_SIZE = "1440*1440"

DASHSCOPE_AIGC_BASE_URL = "https://dashscope.aliyuncs.com/api/v1/services/aigc"
DASHSCOPE_IMAGE_PATH = "/image-generation/generation"
DASHSCOPE_VIDEO_PATH = "/video-generation/video-synthesis"
DASHSCOPE_TASK_URL = "https://dashscope.aliyuncs.com/api/v1/tasks/{task_id}"
DASHSCOPE_IMAGE_MIN_PIXELS = 768 * 768
DASHSCOPE_IMAGE_MAX_PIXELS = 4096 * 4096
DASHSCOPE_IMAGE_EDIT_MAX_PIXELS = 2048 * 2048
DASHSCOPE_IMAGE_MAX_ASPECT_RATIO = 8
DASHSCOPE_VIDEO_MIN_SECONDS = 2.0
DASHSCOPE_VIDEO_MAX_SECONDS = 10.0
DASHSCOPE_VIDEO_MAX_BYTES = 100 * 1024 * 1024
DASHSCOPE_VIDEO_MIN_DIMENSION = 240
DASHSCOPE_VIDEO_MAX_DIMENSION = 4096
DASHSCOPE_VIDEO_MAX_ASPECT_RATIO = 8

IMAGE_EXTENSIONS_BY_MIME = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/webp": "webp",
    "image/gif": "gif",
}
VIDEO_EXTENSIONS_BY_MIME = {
    "video/mp4": "mp4",
    "video/quicktime": "mov",
    "video/webm": "webm",
}
VIDEO_EDIT_EXTENSIONS = {".mp4", ".mov"}
VIDEO_EDIT_MIME_TYPES = {"video/mp4", "video/quicktime", "application/octet-stream"}
PRIVATE_MARKERS = (
    "profiles/",
    "kanban.md",
    "kanban-archive.md",
    "agent-profile.yaml",
    "SKILL.md",
    "evidence-pool.yaml",
    "resume-source.yaml",
    "auth/users.yaml",
)


class VisualGenerationError(RuntimeError):
    """Raised when a visual asset cannot be generated safely."""


@dataclass
class VisualPrompt:
    """Structured prompt metadata for a visual generation request."""

    positive_prompt: str
    negative_prompt: str
    asset_type: str
    recommended_size: str
    rationale: str
    safety_notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly prompt representation."""
        return {
            "positive_prompt": self.positive_prompt,
            "negative_prompt": self.negative_prompt,
            "asset_type": self.asset_type,
            "recommended_size": self.recommended_size,
            "rationale": self.rationale,
            "safety_notes": list(self.safety_notes),
        }


@dataclass
class GeneratedVisualAsset:
    """Generated bytes plus the metadata needed to persist them."""

    data: bytes
    mime_type: str
    extension: str
    prompt: VisualPrompt
    provider: str
    model: str
    source: str = ""


def _env(primary: str, alias: str = "", default: str = "") -> str:
    value = os.getenv(primary)
    if value is None and alias:
        value = os.getenv(alias)
    return str(value if value is not None else default).strip()


def _mask_key(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "set"
    return f"{value[:4]}...{value[-4:]}"


def _configured_key() -> tuple[str, str]:
    for name in ("VISUAL_API_KEY", "DASHSCOPE_API_KEY"):
        value = os.getenv(name, "").strip()
        if value:
            return value, name
    value = llm.api_key_unmasked().strip() or os.getenv("LLM_API_KEY", "").strip()
    if value:
        return value, "LLM_API_KEY"
    return "", ""


def _dashscope_aigc_base_from_llm(url: str) -> str:
    if not llm.is_dashscope_base_url(url):
        return DASHSCOPE_AIGC_BASE_URL
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        return DASHSCOPE_AIGC_BASE_URL
    return f"{parsed.scheme}://{parsed.netloc}/api/v1/services/aigc"


def _configured_base_url() -> tuple[str, str]:
    visual_base = os.getenv("VISUAL_BASE_URL", "").strip()
    if visual_base:
        return visual_base.rstrip("/"), "VISUAL_BASE_URL"
    dashscope_base = os.getenv("DASHSCOPE_BASE_URL", "").strip()
    if dashscope_base:
        return dashscope_base.rstrip("/"), "DASHSCOPE_BASE_URL"
    llm_base = llm.base_url().strip()
    if llm_base and llm.is_dashscope_base_url(llm_base):
        return _dashscope_aigc_base_from_llm(llm_base), "LLM_BASE_URL"
    return DASHSCOPE_AIGC_BASE_URL, "default"


def _endpoint_for(base_url: str, asset_type: str) -> str:
    clean = base_url.rstrip("/")
    image_suffix = DASHSCOPE_IMAGE_PATH.strip("/")
    video_suffix = DASHSCOPE_VIDEO_PATH.strip("/")
    if clean.endswith(image_suffix):
        if asset_type != "video_edit":
            return clean
        return clean[: -len(image_suffix)].rstrip("/") + DASHSCOPE_VIDEO_PATH
    if clean.endswith(video_suffix):
        if asset_type == "video_edit":
            return clean
        return clean[: -len(video_suffix)].rstrip("/") + DASHSCOPE_IMAGE_PATH
    path = DASHSCOPE_VIDEO_PATH if asset_type == "video_edit" else DASHSCOPE_IMAGE_PATH
    return clean + path


def _dashscope_http_base_for_upload(base_url: str) -> str:
    """Return the DashScope API root used by temporary OSS upload certificates."""
    clean = str(base_url or "").strip().rstrip("/")
    if not clean:
        return "https://dashscope.aliyuncs.com/api/v1"
    for suffix in (
        "/services/aigc/video-generation/video-synthesis",
        "/services/aigc/image-generation/generation",
        "/services/aigc",
    ):
        if clean.endswith(suffix):
            return clean[: -len(suffix)].rstrip("/")
    return clean


def current_config(*, mask_key: bool = True) -> dict[str, Any]:
    """Return the current visual-generation configuration."""
    provider = _env("VISUAL_PROVIDER", "IMAGE_PROVIDER", DEFAULT_PROVIDER)
    key, key_source = _configured_key()
    base_url, base_source = _configured_base_url()
    warnings: list[str] = []
    if provider != DEFAULT_PROVIDER:
        warnings.append(
            f"Visual provider '{provider}' is not implemented yet. "
            f"Only '{DEFAULT_PROVIDER}' is currently available."
        )
    if not key:
        warnings.append(
            "Missing visual API key. Set VISUAL_API_KEY, DASHSCOPE_API_KEY, or LLM_API_KEY."
        )
    if base_source == "default" and llm.api_key_unmasked() and not llm.is_dashscope_base_url(
        llm.base_url()
    ):
        warnings.append(
            "LLM_API_KEY will be reused, but LLM_BASE_URL is not a DashScope endpoint; "
            "using the default DashScope visual task endpoint."
        )
    key_value = _mask_key(key) if mask_key else key
    return {
        "provider": provider,
        "api_key": key_value,
        "api_key_source": key_source,
        "base_url": base_url,
        "base_url_source": base_source,
        "image_model": _env("VISUAL_IMAGE_MODEL", "IMAGE_MODEL", DEFAULT_IMAGE_MODEL),
        "image_fast_model": _env(
            "VISUAL_IMAGE_FAST_MODEL",
            "IMAGE_FAST_MODEL",
            DEFAULT_IMAGE_FAST_MODEL,
        ),
        "image_legacy_model": _env(
            "VISUAL_IMAGE_LEGACY_MODEL",
            "IMAGE_LEGACY_MODEL",
            DEFAULT_IMAGE_LEGACY_MODEL,
        ),
        "video_model": _env("VISUAL_VIDEO_MODEL", "IMAGE_VIDEO_MODEL", DEFAULT_VIDEO_MODEL),
        "default_cover_size": _env(
            "VISUAL_DEFAULT_COVER_SIZE",
            "IMAGE_DEFAULT_COVER_SIZE",
            DEFAULT_COVER_SIZE,
        ),
        "default_diagram_size": _env(
            "VISUAL_DEFAULT_DIAGRAM_SIZE",
            "IMAGE_DEFAULT_DIAGRAM_SIZE",
            DEFAULT_DIAGRAM_SIZE,
        ),
        "default_example_size": _env(
            "VISUAL_DEFAULT_EXAMPLE_SIZE",
            "IMAGE_DEFAULT_EXAMPLE_SIZE",
            DEFAULT_EXAMPLE_SIZE,
        ),
        "configured": bool(key) and provider == DEFAULT_PROVIDER,
        "warnings": warnings,
    }


def _strip_private_markers(text: str) -> tuple[str, list[str]]:
    clean = str(text or "")
    notes: list[str] = []
    for marker in PRIVATE_MARKERS:
        if marker in clean:
            clean = clean.replace(marker, "internal reference")
            notes.append(f"Generalized private marker: {marker}")
    clean = re.sub(r"\bprofiles/[^\s)`'\"]+", "internal profile path", clean)
    return clean, notes


def _context_excerpt(value: str, limit: int = 900) -> str:
    clean = re.sub(r"\s+", " ", str(value or "")).strip()
    return clean[:limit]


def build_blog_visual_prompt(
    asset_type: str,
    prompt: str,
    *,
    style: str = "",
    size: str = "",
    title: str = "",
    summary: str = "",
    tags: list[str] | None = None,
    body: str = "",
) -> VisualPrompt:
    """Build a structured, privacy-aware prompt for a blog visual."""
    clean_type = str(asset_type or "").strip().lower() or "cover"
    if clean_type not in {"flowchart", "cover", "example", "video_edit"}:
        raise VisualGenerationError(
            "Visual asset_type must be flowchart, cover, example, or video_edit."
        )
    safe_prompt, notes = _strip_private_markers(prompt)
    safe_title, title_notes = _strip_private_markers(title)
    safe_summary, summary_notes = _strip_private_markers(summary)
    safe_body, body_notes = _strip_private_markers(body)
    notes.extend(title_notes + summary_notes + body_notes)
    tags_text = ", ".join(str(tag).strip() for tag in (tags or []) if str(tag).strip())
    style_text = str(style or "").strip()
    config = current_config()
    if clean_type == "cover":
        recommended = size or str(config["default_cover_size"])
        positive = (
            "Editorial cover image for a public technical blog post. "
            "Use a strong, inspectable subject, layered depth, and generous negative space "
            "for an HTML/CSS title overlay. Do not embed title text in the image. "
            f"Blog title: {safe_title or 'untitled post'}. "
            f"Summary: {safe_summary or _context_excerpt(safe_body, 260)}. "
            f"Tags: {tags_text or 'general technical writing'}. "
            f"User visual brief: {safe_prompt}."
        )
        negative = "embedded text, watermark, logo, misspelled words, tiny text, clutter, low contrast"
        rationale = "Cover art should support the article header while leaving the title to HTML."
    elif clean_type == "flowchart":
        recommended = size or str(config["default_diagram_size"])
        positive = (
            "Clean vector-style process diagram with rectangular boxes, clear arrows, "
            "high contrast, readable hierarchy, and generous spacing. "
            "Use simple labels only if needed; no tiny text. "
            f"Diagram content brief: {safe_prompt}. "
            f"Blog context: {safe_title or _context_excerpt(safe_summary or safe_body, 240)}."
        )
        negative = "tiny text, watermark, decorative clutter, illegible labels, tangled arrows"
        rationale = "Flowcharts need controlled boxes and arrows more than painterly detail."
    elif clean_type == "example":
        recommended = size or str(config["default_example_size"])
        positive = (
            "Clear example illustration for a public technical article. "
            "Make the system, scenario, or workflow easy to inspect; avoid excessive abstraction. "
            f"Example brief: {safe_prompt}. "
            f"Blog context: {safe_title or _context_excerpt(safe_summary or safe_body, 260)}."
        )
        negative = "private names, private file paths, watermark, unreadable text, vague abstraction"
        rationale = "Example images should make the post's scenario concrete and reviewable."
    else:
        recommended = size or "source-video"
        positive = (
            "Video edit instruction for a public blog visual candidate. "
            "Keep edits factual, clean, and presentation-ready. "
            f"Edit brief: {safe_prompt}."
        )
        negative = "watermark, private identifiers, unreadable captions, unsafe content"
        rationale = "Video edits are only run when the user explicitly requests them."
    if style_text:
        positive += f" Preferred style: {style_text}."
    return VisualPrompt(
        positive_prompt=positive,
        negative_prompt=negative,
        asset_type=clean_type,
        recommended_size=recommended,
        rationale=rationale,
        safety_notes=notes,
    )


def _clean_caption_text(value: Any, *, limit: int = 1200) -> str:
    clean = re.sub(r"\s+", " ", str(value or "")).strip()
    return clean[:limit]


def _strip_response_fence(value: str) -> str:
    text = str(value or "").strip()
    fence = re.fullmatch(r"```(?:json|JSON|[a-zA-Z0-9_-]+)?\s*(.*?)\s*```", text, re.S)
    if fence:
        return fence.group(1).strip()
    return text


def _caption_fallback(value: str, source_text: str = "") -> str:
    clean = _clean_caption_text(value or source_text, limit=220)
    if not clean:
        return "Illustration for the article context."
    sentence = re.split(r"(?<=[.!?。！？])\s+", clean, maxsplit=1)[0].strip()
    return sentence[:220] or clean[:220]


def parse_caption_intent_response(response: str, *, source_text: str = "") -> dict[str, Any]:
    """Parse an LLM caption-intent response into prompt/caption/alt fields.

    The preferred response is JSON, but the parser also accepts plain text or
    labeled lines so tests and fallbacks do not need a configured model.
    """
    text = _strip_response_fence(response)
    loaded: Any = None
    warnings: list[str] = []
    if text:
        try:
            loaded = json.loads(text)
        except Exception:
            loaded = None
    if isinstance(loaded, dict):
        prompt = _clean_caption_text(
            loaded.get("prompt")
            or loaded.get("visual_prompt")
            or loaded.get("image_prompt")
            or loaded.get("positive_prompt"),
            limit=1600,
        )
        caption = _clean_caption_text(loaded.get("caption"), limit=220)
        alt = _clean_caption_text(loaded.get("alt") or loaded.get("alt_text"), limit=220)
        raw_warnings = loaded.get("warnings") or loaded.get("safety_notes") or []
        if isinstance(raw_warnings, list):
            warnings.extend(_clean_caption_text(item, limit=220) for item in raw_warnings)
        elif raw_warnings:
            warnings.append(_clean_caption_text(raw_warnings, limit=220))
    else:
        labeled: dict[str, str] = {}
        for raw_line in text.splitlines():
            match = re.match(r"^\s*(prompt|visual_prompt|image_prompt|caption|alt|alt_text)\s*:\s*(.+?)\s*$", raw_line, re.I)
            if match:
                labeled[match.group(1).lower()] = match.group(2).strip()
        prompt = _clean_caption_text(
            labeled.get("prompt")
            or labeled.get("visual_prompt")
            or labeled.get("image_prompt")
            or text
            or source_text,
            limit=1600,
        )
        caption = _clean_caption_text(labeled.get("caption"), limit=220)
        alt = _clean_caption_text(labeled.get("alt") or labeled.get("alt_text"), limit=220)
    if not prompt:
        prompt = (
            "Clear example illustration for a public technical article. "
            f"Concrete subject from context: {_caption_fallback(source_text)}."
        )
    if not caption:
        caption = _caption_fallback(source_text or prompt)
    if not alt:
        alt = caption or _caption_fallback(prompt)
    return {
        "prompt": prompt,
        "caption": caption,
        "alt": alt,
        "warnings": [warning for warning in warnings if warning],
    }


def _caption_user_payload(
    *,
    text: str,
    lang: str,
    title: str = "",
    summary: str = "",
    tags: list[str] | None = None,
    body: str = "",
) -> str:
    payload = {
        "operation": "visual_caption",
        "instruction": get_prompt("caption", lang),
        "target_text": _clean_caption_text(text, limit=1800),
        "title": _clean_caption_text(title, limit=240),
        "summary": _clean_caption_text(summary, limit=600),
        "tags": [str(tag).strip() for tag in (tags or []) if str(tag).strip()],
        "article_excerpt": _clean_caption_text(body, limit=1800),
        "response_format": {
            "prompt": "visual generation prompt",
            "caption": "short display caption",
            "alt": "accessible alt text",
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def from_caption_intent(text: str, lang: str = "en", **context: Any) -> dict[str, Any]:
    """Create an example visual candidate from prose or a caption-intent reply.

    Returns a structured dict even when LLM or visual generation is not
    configured.  Provider/network errors are converted to warnings so callers
    can still persist a visual-block prompt candidate.
    """
    prompt_lang = "zh" if str(lang or "").strip().lower() == "zh" else "en"
    warnings: list[str] = []
    raw_response = str(
        context.pop("llm_response", "") or context.pop("raw_response", "") or ""
    ).strip()
    chat_func = context.pop("chat_func", None)
    title = str(context.get("title") or "").strip()
    summary = str(context.get("summary") or "").strip()
    body = str(context.get("body") or context.get("markdown") or "").strip()
    style = str(context.get("style") or "").strip()
    size = str(context.get("size") or "").strip()
    tags_value = context.get("tags")
    tags = [str(tag).strip() for tag in tags_value if str(tag).strip()] if isinstance(tags_value, list) else []

    if not raw_response:
        if chat_func is not None or llm.is_configured():
            try:
                chat = chat_func or llm.chat
                raw_response = chat(
                    get_prompt("inline_system", prompt_lang),
                    _caption_user_payload(
                        text=text,
                        lang=prompt_lang,
                        title=title,
                        summary=summary,
                        tags=tags,
                        body=body,
                    ),
                    temperature=0.25,
                )
            except Exception as exc:
                warnings.append(f"Caption intent LLM failed: {exc}")
                raw_response = ""
            if raw_response.startswith("LLM error:") or raw_response.startswith(
                "AI features not configured."
            ):
                warnings.append(raw_response)
                raw_response = ""
        else:
            warnings.append("AI features not configured; using text fallback for visual prompt.")

    intent = parse_caption_intent_response(raw_response, source_text=text)
    warnings.extend(str(warning) for warning in intent.get("warnings", []) if warning)
    result: dict[str, Any] = {
        "asset_type": "image",
        "visual_kind": "example",
        "prompt": str(intent.get("prompt") or "").strip(),
        "caption": str(intent.get("caption") or "").strip(),
        "alt": str(intent.get("alt") or "").strip(),
        "status": "candidate",
        "src": "",
        "provider": DEFAULT_PROVIDER,
        "model": "",
        "warnings": [],
        "assets": [],
        "generated_assets": [],
    }
    try:
        generated_assets = generate_visual_asset(
            "example",
            result["prompt"],
            style=style,
            size=size,
            title=title,
            summary=summary,
            tags=tags,
            body=body or text,
        )
    except VisualGenerationError as exc:
        warnings.append(str(exc))
        generated_assets = []
    except Exception as exc:
        warnings.append(f"Visual generation failed: {exc}")
        generated_assets = []

    if generated_assets:
        first = generated_assets[0]
        result.update(
            {
                "status": "generated",
                "src": first.source if first.source.startswith(("http://", "https://")) else "",
                "provider": first.provider,
                "model": first.model,
                "mime_type": first.mime_type,
                "extension": first.extension,
                "generated_assets": generated_assets,
            }
        )
    result["assets"] = [
        {
            "kind": "image",
            "src": result["src"],
            "prompt": result["prompt"],
            "provider": result["provider"],
            "model": result["model"],
        }
    ]
    result["warnings"] = [warning for warning in warnings if warning]
    return result


def _contains_oss_url(value: Any) -> bool:
    if isinstance(value, str):
        return value.strip().startswith("oss://")
    if isinstance(value, dict):
        return any(_contains_oss_url(item) for item in value.values())
    if isinstance(value, list):
        return any(_contains_oss_url(item) for item in value)
    return False


def _request_json(
    url: str,
    payload: dict[str, Any],
    api_key: str,
    *,
    resolve_oss: bool = False,
) -> dict[str, Any]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "X-DashScope-Async": "enable",
    }
    if resolve_oss:
        headers["X-DashScope-OssResourceResolve"] = "enable"
    request = Request(
        url,
        data=data,
        method="POST",
        headers=headers,
    )
    try:
        with urlopen(request, timeout=60) as response:
            raw = response.read().decode("utf-8")
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise VisualGenerationError(f"DashScope visual API error: {exc.code} {detail}") from exc
    except URLError as exc:
        raise VisualGenerationError(f"DashScope visual API request failed: {exc}") from exc
    try:
        loaded = json.loads(raw)
    except Exception as exc:
        raise VisualGenerationError("DashScope visual API returned non-JSON data") from exc
    if not isinstance(loaded, dict):
        raise VisualGenerationError("DashScope visual API returned an invalid response")
    return loaded


def _get_json(url: str, api_key: str) -> dict[str, Any]:
    request = Request(url, headers={"Authorization": f"Bearer {api_key}"})
    try:
        with urlopen(request, timeout=60) as response:
            raw = response.read().decode("utf-8")
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise VisualGenerationError(f"DashScope task polling error: {exc.code} {detail}") from exc
    except URLError as exc:
        raise VisualGenerationError(f"DashScope task polling failed: {exc}") from exc
    loaded = json.loads(raw)
    if not isinstance(loaded, dict):
        raise VisualGenerationError("DashScope task polling returned an invalid response")
    return loaded


def _poll_task(task_id: str, api_key: str, *, attempts: int = 30) -> dict[str, Any]:
    for _index in range(attempts):
        data = _get_json(DASHSCOPE_TASK_URL.format(task_id=task_id), api_key)
        status = str(data.get("output", {}).get("task_status", "") or "").upper()
        if status in {"SUCCEEDED", "FAILED", "CANCELED", "UNKNOWN"}:
            if status != "SUCCEEDED":
                message = data.get("message") or data.get("output", {}).get("message") or status
                raise VisualGenerationError(f"DashScope visual task failed: {message}")
            return data
        time.sleep(2)
    raise VisualGenerationError("DashScope visual task did not finish in time")


def _walk(value: Any):
    if isinstance(value, dict):
        yield value
        for item in value.values():
            yield from _walk(item)
    elif isinstance(value, list):
        for item in value:
            yield from _walk(item)


def _extract_urls(response: dict[str, Any]) -> list[str]:
    urls: list[str] = []
    for item in _walk(response):
        for key in ("url", "image", "video", "image_url", "video_url", "output_url"):
            value = item.get(key)
            if isinstance(value, str) and value.strip().startswith(("http://", "https://")):
                urls.append(value.strip())
    return urls


def _extract_base64(response: dict[str, Any]) -> list[str]:
    values: list[str] = []
    for item in _walk(response):
        for key in ("base64", "image_base64", "b64_json", "data"):
            value = item.get(key)
            if isinstance(value, str) and value.strip():
                values.append(value.strip())
    return values


def _download(url: str) -> tuple[bytes, str]:
    request = Request(url, headers={"User-Agent": "nblane/visual-generation"})
    try:
        with urlopen(request, timeout=120) as response:
            data = response.read()
            mime = response.headers.get_content_type() or ""
    except HTTPError as exc:
        raise VisualGenerationError(f"Generated asset download failed: HTTP {exc.code}") from exc
    except URLError as exc:
        raise VisualGenerationError(f"Generated asset download failed: {exc}") from exc
    if not mime or mime == "application/octet-stream":
        mime = mimetypes.guess_type(urlparse(url).path)[0] or ""
    return data, mime


def _head_video_source(url: str) -> dict[str, Any]:
    """Return cheap metadata for a remote video URL when the server allows it."""
    parsed = urlparse(str(url or ""))
    if parsed.scheme not in {"http", "https"}:
        return {}
    request = Request(
        url,
        method="HEAD",
        headers={"User-Agent": "nblane/visual-generation"},
    )
    try:
        with urlopen(request, timeout=20) as response:
            length = response.headers.get("Content-Length", "")
            return {
                "mime_type": response.headers.get_content_type() or "",
                "size": int(length) if str(length).isdigit() else None,
            }
    except HTTPError as exc:
        if exc.code not in {403, 405}:
            raise VisualGenerationError(
                f"Source video URL is not reachable: HTTP {exc.code}."
            ) from exc
    except URLError as exc:
        raise VisualGenerationError(f"Source video URL is not reachable: {exc}") from exc
    return {}


def _ffprobe_video_source(url: str) -> dict[str, Any]:
    """Probe video duration and dimensions if ffprobe is available."""
    executable = shutil.which("ffprobe")
    if not executable:
        return {}
    command = [
        executable,
        "-v",
        "error",
        "-show_entries",
        "format=duration,size",
        "-show_entries",
        "stream=codec_type,width,height",
        "-of",
        "json",
        url,
    ]
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return {}
    if completed.returncode != 0:
        return {}
    try:
        loaded = json.loads(completed.stdout or "{}")
    except Exception:
        return {}
    if not isinstance(loaded, dict):
        return {}
    info: dict[str, Any] = {}
    fmt = loaded.get("format")
    if isinstance(fmt, dict):
        info["duration"] = fmt.get("duration")
        info["size"] = fmt.get("size")
    for stream in loaded.get("streams", []):
        if isinstance(stream, dict) and stream.get("codec_type") == "video":
            info["width"] = stream.get("width")
            info["height"] = stream.get("height")
            break
    return info


def _probe_video_source(url: str) -> dict[str, Any]:
    """Collect best-effort source-video metadata without starting a provider task."""
    info = _head_video_source(url)
    for key, value in _ffprobe_video_source(url).items():
        if value not in {None, ""}:
            info[key] = value
    return info


def _optional_float(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if number == number else None


def _optional_int(value: Any) -> int | None:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def _local_file_path(value: str) -> Path | None:
    clean = str(value or "").strip()
    if not clean:
        return None
    parsed = urlparse(clean)
    if parsed.scheme in {"http", "https", "oss"}:
        return None
    if parsed.scheme == "file":
        path_text = unquote(parsed.path or "")
        if parsed.netloc:
            path_text = f"//{parsed.netloc}{path_text}"
        path = Path(path_text).expanduser()
    else:
        path = Path(clean).expanduser()
    return path if path.exists() and path.is_file() else None


def _validate_video_dimensions(info: dict[str, Any]) -> None:
    width = _optional_int(info.get("width"))
    height = _optional_int(info.get("height"))
    if width and height:
        min_dim = min(width, height)
        max_dim = max(width, height)
        if (
            min_dim < DASHSCOPE_VIDEO_MIN_DIMENSION
            or max_dim > DASHSCOPE_VIDEO_MAX_DIMENSION
        ):
            raise VisualGenerationError(
                "DashScope video edit source_video dimensions must be between "
                f"{DASHSCOPE_VIDEO_MIN_DIMENSION}px and "
                f"{DASHSCOPE_VIDEO_MAX_DIMENSION}px; got {width}x{height}."
            )
        ratio = max_dim / min_dim
        if ratio > DASHSCOPE_VIDEO_MAX_ASPECT_RATIO:
            raise VisualGenerationError(
                "DashScope video edit source_video aspect ratio must stay between "
                "1:8 and 8:1."
            )


def _validate_video_edit_source(source_video: str) -> None:
    """Fail early for source videos DashScope video edit cannot ingest."""
    clean = str(source_video or "").strip()
    if not clean:
        raise VisualGenerationError("Video edit generation requires a source_video URL.")
    parsed = urlparse(clean)
    local_path = _local_file_path(clean)
    if parsed.scheme == "oss":
        return
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        if not local_path:
            raise VisualGenerationError(
                "DashScope video edit requires a public HTTP(S), oss://, or existing "
                "local source_video file."
            )
        suffix = local_path.suffix.lower()
    else:
        suffix = Path(parsed.path).suffix.lower()
    if suffix and suffix not in VIDEO_EDIT_EXTENSIONS:
        allowed = ", ".join(sorted(VIDEO_EDIT_EXTENSIONS))
        raise VisualGenerationError(
            f"DashScope video edit source_video must be MP4 or MOV ({allowed})."
        )
    if local_path:
        stat_size = local_path.stat().st_size
        if stat_size > DASHSCOPE_VIDEO_MAX_BYTES:
            limit_mb = DASHSCOPE_VIDEO_MAX_BYTES // (1024 * 1024)
            actual_mb = stat_size / (1024 * 1024)
            raise VisualGenerationError(
                f"DashScope video edit source_video must be at most {limit_mb}MB; "
                f"this local file is about {actual_mb:.1f}MB."
            )
        info = _probe_video_source(str(local_path))
    else:
        info = _probe_video_source(clean)
    mime = str(info.get("mime_type", "") or "").lower()
    if mime and mime not in VIDEO_EDIT_MIME_TYPES:
        raise VisualGenerationError(
            f"DashScope video edit source_video must be MP4 or MOV, got {mime}."
        )
    size = _optional_int(info.get("size"))
    if size is not None and size > DASHSCOPE_VIDEO_MAX_BYTES:
        limit_mb = DASHSCOPE_VIDEO_MAX_BYTES // (1024 * 1024)
        actual_mb = size / (1024 * 1024)
        raise VisualGenerationError(
            f"DashScope video edit source_video must be at most {limit_mb}MB; "
            f"this URL is about {actual_mb:.1f}MB."
        )
    duration = _optional_float(info.get("duration"))
    if duration is not None and not (
        DASHSCOPE_VIDEO_MIN_SECONDS <= duration <= DASHSCOPE_VIDEO_MAX_SECONDS
    ):
        source_label = "local file" if local_path else "URL"
        raise VisualGenerationError(
            "DashScope video edit source_video must be 2-10 seconds. "
            f"This {source_label} is about {duration:.1f}s; trim/export a 2-10s clip "
            "and try again."
        )
    _validate_video_dimensions(info)


def _upload_dashscope_local_file(
    path: Path,
    *,
    model: str,
    api_key: str,
    base_url: str,
) -> str:
    """Upload a local file to DashScope temporary OSS and return an oss:// URL."""
    upload_base = _dashscope_http_base_for_upload(base_url)
    upload_info = _dashscope_upload_certificate(
        model=model,
        api_key=api_key,
        upload_base=upload_base,
    )
    return _post_dashscope_oss_file(path, upload_info)


def _dashscope_upload_certificate(
    *,
    model: str,
    api_key: str,
    upload_base: str,
) -> dict[str, Any]:
    url = (
        upload_base.rstrip("/")
        + "/uploads?action=getPolicy&model="
        + quote(str(model or ""), safe="")
    )
    request = Request(
        url,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Accept": "application/json",
            "User-Agent": "nblane/visual-generation",
        },
    )
    try:
        with urlopen(request, timeout=60) as response:
            raw = response.read().decode("utf-8")
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise VisualGenerationError(
            f"DashScope upload certificate request failed: HTTP {exc.code} {detail}"
        ) from exc
    except URLError as exc:
        raise VisualGenerationError(
            f"DashScope upload certificate request failed: {exc}"
        ) from exc
    try:
        loaded = json.loads(raw)
    except Exception as exc:
        raise VisualGenerationError(
            "DashScope upload certificate response was not valid JSON"
        ) from exc
    if not isinstance(loaded, dict):
        raise VisualGenerationError("DashScope upload certificate response was invalid")
    if isinstance(loaded.get("output"), dict):
        output = loaded["output"]
    elif isinstance(loaded.get("data"), dict):
        output = loaded["data"]
    else:
        output = loaded
    required = {
        "oss_access_key_id",
        "signature",
        "policy",
        "upload_dir",
        "x_oss_object_acl",
        "x_oss_forbid_overwrite",
        "upload_host",
    }
    missing = sorted(key for key in required if not output.get(key))
    if missing:
        raise VisualGenerationError(
            f"DashScope upload certificate is missing fields: {', '.join(missing)}"
        )
    return dict(output)


def _multipart_form_body(
    fields: dict[str, str],
    *,
    file_field: str,
    filename: str,
    mime_type: str,
    data: bytes,
) -> tuple[bytes, str]:
    boundary = f"----nblane-dashscope-{uuid.uuid4().hex}"
    chunks: list[bytes] = []
    for name, value in fields.items():
        chunks.extend(
            [
                f"--{boundary}\r\n".encode("utf-8"),
                f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode("utf-8"),
                str(value).encode("utf-8"),
                b"\r\n",
            ]
        )
    chunks.extend(
        [
            f"--{boundary}\r\n".encode("utf-8"),
            (
                f'Content-Disposition: form-data; name="{file_field}"; '
                f'filename="{filename}"\r\n'
            ).encode("utf-8"),
            f"Content-Type: {mime_type or 'application/octet-stream'}\r\n\r\n".encode(
                "utf-8"
            ),
            data,
            b"\r\n",
            f"--{boundary}--\r\n".encode("utf-8"),
        ]
    )
    return b"".join(chunks), boundary


def _post_dashscope_oss_file(path: Path, upload_info: dict[str, Any]) -> str:
    filename = path.name
    upload_key = f"{upload_info['upload_dir']}/{filename}"
    mime_type = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
    fields = {
        "OSSAccessKeyId": str(upload_info["oss_access_key_id"]),
        "Signature": str(upload_info["signature"]),
        "policy": str(upload_info["policy"]),
        "key": upload_key,
        "x-oss-object-acl": str(upload_info["x_oss_object_acl"]),
        "x-oss-forbid-overwrite": str(upload_info["x_oss_forbid_overwrite"]),
        "success_action_status": "200",
        "x-oss-content-type": mime_type,
    }
    body, boundary = _multipart_form_body(
        fields,
        file_field="file",
        filename=filename,
        mime_type=mime_type,
        data=path.read_bytes(),
    )
    request = Request(
        str(upload_info["upload_host"]),
        data=body,
        method="POST",
        headers={
            "Accept": "application/json",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Content-Length": str(len(body)),
            "Date": formatdate(usegmt=True),
            "User-Agent": "nblane/visual-generation",
        },
    )
    try:
        with urlopen(request, timeout=3600) as response:
            response.read()
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise VisualGenerationError(
            f"Uploading local media to DashScope temporary OSS failed: "
            f"HTTP {exc.code} {detail}"
        ) from exc
    except URLError as exc:
        raise VisualGenerationError(
            f"Uploading local media to DashScope temporary OSS failed: {exc}"
        ) from exc
    return f"oss://{upload_key}"


def _prepare_dashscope_media_url(
    value: str,
    *,
    model: str,
    api_key: str,
    base_url: str,
) -> str:
    clean = str(value or "").strip()
    if not clean:
        return ""
    parsed = urlparse(clean)
    if parsed.scheme in {"http", "https", "oss"}:
        return clean
    local_path = _local_file_path(clean)
    if not local_path:
        return clean
    return _upload_dashscope_local_file(
        local_path,
        model=model,
        api_key=api_key,
        base_url=base_url,
    )


def _decode_data_url(value: str) -> tuple[bytes, str]:
    clean = value.strip()
    if clean.startswith("data:") and ";base64," in clean:
        header, encoded = clean.split(",", 1)
        mime = header[5:].split(";", 1)[0]
    else:
        encoded = clean
        mime = ""
    try:
        data = base64.b64decode(re.sub(r"\s+", "", encoded), validate=True)
    except Exception as exc:
        raise VisualGenerationError("Generated asset base64 payload is invalid") from exc
    return data, mime


def _sniff_mime(data: bytes, fallback: str = "") -> str:
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if data.startswith(b"RIFF") and data[8:12] == b"WEBP":
        return "image/webp"
    if data.startswith((b"GIF87a", b"GIF89a")):
        return "image/gif"
    if len(data) > 12 and data[4:8] == b"ftyp":
        return "video/mp4"
    return fallback or "application/octet-stream"


def _asset_extension(data: bytes, mime: str, asset_type: str) -> tuple[str, str]:
    clean_mime = _sniff_mime(data, mime)
    if asset_type == "video_edit":
        ext = VIDEO_EXTENSIONS_BY_MIME.get(clean_mime)
    else:
        ext = IMAGE_EXTENSIONS_BY_MIME.get(clean_mime)
    if not ext:
        raise VisualGenerationError(f"Generated asset has unsupported MIME type: {clean_mime}")
    return clean_mime, ext


def _uses_legacy_image_payload(model: str) -> bool:
    clean = str(model or "").strip().lower()
    return clean.startswith(("wan2.1-", "wanx2.1-"))


def _image_max_pixels(model: str, *, has_reference_image: bool) -> int:
    clean = str(model or "").strip().lower()
    if clean == DEFAULT_IMAGE_MODEL and not has_reference_image:
        return DASHSCOPE_IMAGE_MAX_PIXELS
    return DASHSCOPE_IMAGE_EDIT_MAX_PIXELS


def _normalize_image_size(
    size: str,
    *,
    model: str,
    has_reference_image: bool = False,
) -> str:
    """Normalize and validate DashScope image size parameters."""
    clean = str(size or "").strip()
    if not clean:
        return ""
    clean = clean.replace("×", "x")
    shortcut = clean.upper()
    if shortcut in {"1K", "2K", "4K"}:
        if shortcut == "4K" and _image_max_pixels(
            model,
            has_reference_image=has_reference_image,
        ) < DASHSCOPE_IMAGE_MAX_PIXELS:
            raise VisualGenerationError(
                "DashScope 4K image size is only available for wan2.7-image-pro "
                "text-to-image requests without reference images."
            )
        return shortcut
    match = re.fullmatch(r"(\d+)\s*[xX]\s*(\d+)", clean)
    if match:
        clean = f"{match.group(1)}*{match.group(2)}"
    match = re.fullmatch(r"(\d+)\s*\*\s*(\d+)", clean)
    if not match:
        raise VisualGenerationError(
            "DashScope image size must use width*height, such as 1536*864, "
            "or one of 1K, 2K, 4K."
        )
    width = int(match.group(1))
    height = int(match.group(2))
    if width <= 0 or height <= 0:
        raise VisualGenerationError("DashScope image width and height must be positive.")
    total = width * height
    if total < DASHSCOPE_IMAGE_MIN_PIXELS:
        raise VisualGenerationError(
            "DashScope image size is too small: total pixels must be at least "
            "768*768. Use 768*768, 1024*1024, 1536*864, or leave Size empty."
        )
    max_pixels = _image_max_pixels(model, has_reference_image=has_reference_image)
    if total > max_pixels:
        max_label = "4096*4096" if max_pixels == DASHSCOPE_IMAGE_MAX_PIXELS else "2048*2048"
        raise VisualGenerationError(
            f"DashScope image size is too large for this request: total pixels "
            f"must be at most {max_label}."
        )
    ratio = max(width, height) / min(width, height)
    if ratio > DASHSCOPE_IMAGE_MAX_ASPECT_RATIO:
        raise VisualGenerationError(
            "DashScope image aspect ratio must stay between 1:8 and 8:1."
        )
    return f"{width}*{height}"


def _dashscope_image_prompt_text(prompt: VisualPrompt) -> str:
    text = prompt.positive_prompt.strip()
    if prompt.negative_prompt.strip():
        text += f"\n\nAvoid: {prompt.negative_prompt.strip()}."
    return text


def _dashscope_payload(
    prompt: VisualPrompt,
    *,
    asset_type: str,
    model: str,
    size: str,
    source_video: str = "",
    reference_image: str = "",
) -> dict[str, Any]:
    if asset_type == "video_edit":
        input_data: dict[str, Any] = {
            "prompt": prompt.positive_prompt,
            "negative_prompt": prompt.negative_prompt,
        }
        media = [{"type": "video", "url": source_video}]
        if reference_image:
            media.append({"type": "reference_image", "url": reference_image})
        input_data["media"] = media
        return {
            "model": model,
            "input": input_data,
            "parameters": {
                "resolution": "720P",
                "watermark": False,
            },
        }

    normalized_size = _normalize_image_size(
        size,
        model=model,
        has_reference_image=bool(reference_image),
    )
    parameters: dict[str, Any] = {
        "n": 1,
        "watermark": False,
    }
    if normalized_size:
        parameters["size"] = normalized_size
    if _uses_legacy_image_payload(model):
        input_data = {
            "prompt": _dashscope_image_prompt_text(prompt),
        }
        if reference_image:
            input_data["image_url"] = reference_image
        return {
            "model": model,
            "input": input_data,
            "parameters": parameters,
        }

    content: list[dict[str, str]] = []
    if reference_image:
        content.append({"image": reference_image})
    content.append({"text": _dashscope_image_prompt_text(prompt)})
    return {
        "model": model,
        "input": {
            "messages": [
                {
                    "role": "user",
                    "content": content,
                }
            ],
        },
        "parameters": parameters,
    }


def generate_visual_asset(
    asset_type: str,
    prompt: str,
    *,
    style: str = "",
    size: str = "",
    title: str = "",
    summary: str = "",
    tags: list[str] | None = None,
    body: str = "",
    source_video: str = "",
    reference_image: str = "",
) -> list[GeneratedVisualAsset]:
    """Generate one or more visual assets with the configured provider."""
    config = current_config(mask_key=False)
    if not config["configured"]:
        missing = "VISUAL_API_KEY / DASHSCOPE_API_KEY / LLM_API_KEY"
        raise VisualGenerationError(f"Visual generation is not configured. Set {missing}.")
    provider = str(config["provider"])
    if provider != DEFAULT_PROVIDER:
        raise VisualGenerationError(f"Visual provider is not supported yet: {provider}")
    clean_type = str(asset_type or "").strip().lower()
    if clean_type == "video_edit" and not source_video:
        raise VisualGenerationError("Video edit generation requires a source_video URL.")
    if clean_type == "video_edit":
        _validate_video_edit_source(source_video)
    structured = build_blog_visual_prompt(
        clean_type,
        prompt,
        style=style,
        size=size,
        title=title,
        summary=summary,
        tags=tags,
        body=body,
    )
    model = str(config["video_model"] if clean_type == "video_edit" else config["image_model"])
    endpoint = _endpoint_for(str(config["base_url"]), clean_type)
    prepared_source_video = (
        _prepare_dashscope_media_url(
            source_video,
            model=model,
            api_key=str(config["api_key"]),
            base_url=str(config["base_url"]),
        )
        if clean_type == "video_edit"
        else source_video
    )
    prepared_reference_image = (
        _prepare_dashscope_media_url(
            reference_image,
            model=model,
            api_key=str(config["api_key"]),
            base_url=str(config["base_url"]),
        )
        if reference_image
        else ""
    )
    payload = _dashscope_payload(
        structured,
        asset_type=clean_type,
        model=model,
        size=size or structured.recommended_size,
        source_video=prepared_source_video,
        reference_image=prepared_reference_image,
    )
    response = _request_json(
        endpoint,
        payload,
        str(config["api_key"]),
        resolve_oss=_contains_oss_url(payload),
    )
    task_id = str(response.get("output", {}).get("task_id", "") or "")
    if task_id and not (_extract_urls(response) or _extract_base64(response)):
        response = _poll_task(task_id, str(config["api_key"]))
    assets: list[GeneratedVisualAsset] = []
    for value in _extract_base64(response):
        data, mime = _decode_data_url(value)
        mime, ext = _asset_extension(data, mime, clean_type)
        assets.append(
            GeneratedVisualAsset(
                data=data,
                mime_type=mime,
                extension=ext,
                prompt=structured,
                provider=provider,
                model=model,
                source="base64",
            )
        )
    for url in _extract_urls(response):
        data, mime = _download(url)
        mime, ext = _asset_extension(data, mime, clean_type)
        assets.append(
            GeneratedVisualAsset(
                data=data,
                mime_type=mime,
                extension=ext,
                prompt=structured,
                provider=provider,
                model=model,
                source=url,
            )
        )
    if not assets:
        digest = hashlib.sha256(json.dumps(response, sort_keys=True).encode("utf-8")).hexdigest()[:10]
        raise VisualGenerationError(
            f"Visual provider returned no downloadable asset (response {digest})."
        )
    return assets


def generated_filename(asset_type: str, data: bytes, extension: str) -> str:
    """Return the canonical generated media filename."""
    clean_type = re.sub(r"[^A-Za-z0-9_-]+", "-", str(asset_type or "asset")).strip("-")
    clean_type = clean_type or "asset"
    digest = hashlib.sha256(data).hexdigest()[:12]
    return f"generated-{clean_type}-{digest}.{extension.lstrip('.')}"
