#!/usr/bin/env bash
# install.sh — install the repo-provided OpenClaw assets (skills + weixin-task-bridge
# plugin) into the local OpenClaw workspace. Idempotent: safe to re-run.
#
# Usage:
#   scripts/openclaw/install.sh            # perform the install
#   scripts/openclaw/install.sh --dry-run  # print actions without executing
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_SRC="${SCRIPT_DIR}/skills/"
PLUGIN_DIR="${SCRIPT_DIR}/plugins/weixin-task-bridge"
OPENCLAW_WORKSPACE="${OPENCLAW_WORKSPACE:-${HOME}/.openclaw/workspace}"
SKILLS_DST="${OPENCLAW_WORKSPACE}/skills/"

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run]"
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: $0 [--dry-run]" >&2
      exit 2
      ;;
  esac
done

run() {
  if [[ "${DRY_RUN}" -eq 1 ]]; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

echo "==> Syncing skills: ${SKILLS_SRC} -> ${SKILLS_DST}"
run rsync -a --exclude='__pycache__' --exclude='.venv' "${SKILLS_SRC}" "${SKILLS_DST}"

# nblane_api needs httpx, which the system python lacks (PEP 668). Keep a
# dedicated venv inside the synced skills dir and expose a stable wrapper so
# prompts can call `.../skills/bin/nblane_api <cmd>` without absolute paths.
SKILLS_VENV="${SKILLS_DST}/.venv"
if [[ ! -x "${SKILLS_VENV}/bin/python" ]]; then
  echo "==> Creating skills venv: ${SKILLS_VENV}"
  run python3 -m venv "${SKILLS_VENV}"
fi
if ! "${SKILLS_VENV}/bin/python" -c "import httpx" 2>/dev/null; then
  echo "==> Installing httpx into skills venv"
  run "${SKILLS_VENV}/bin/pip" install -q httpx
fi
WRAPPER="${SKILLS_DST}/bin/nblane_api"
if [[ "${DRY_RUN}" -eq 1 ]]; then
  echo "[dry-run] write wrapper ${WRAPPER}"
else
  cat > "${WRAPPER}" <<'WRAP'
#!/usr/bin/env bash
# Generated by install.sh — runs nblane_api.py with the skills venv python.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${HERE}/../.venv/bin/python" "${HERE}/nblane_api.py" "$@"
WRAP
  chmod +x "${WRAPPER}"
fi

echo "==> Installing plugin: ${PLUGIN_DIR}"
run openclaw plugins install "${PLUGIN_DIR}" --force --accept-capabilities

echo ""
echo "Done. Verify with:"
echo "  openclaw plugins inspect weixin-task-bridge --runtime --json"
